name: R spellcheck action
author: Insights Engineering
description: Checks for spelling errors in R packages

branding:
  icon: feather
  color: blue

inputs:
  path:
    description: Path to package root.
    required: false
    default: "."
  exclude:
    description: Comma separated list of files or folders to exclude from spellcheck. Accepts globs.
    required: false
    default: ""
  additional_options:
    description: Additional options to pass to Rscript.
    required: false
    default: --vanilla

runs:
  using: composite
  steps:
      - name: Optionally install the spelling package
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org/"))
          ncores <- parallel::detectCores(all.tests = FALSE, logical = TRUE)
          if (!require("spelling")) install.packages("spelling", upgrade = "never", Ncpus = ncores)
        shell: Rscript {0}

      - name: Check spelling
        run: |
          cd ${{ inputs.path }}
          Rscript ${{ inputs.additional_options }} \
            ${GITHUB_ACTION_PATH}/spellcheck.R \
            ${{ inputs.exclude }}
        shell: bash
